### ISSUE TITLE
Site Dosyaları ve Fonksiyonları Değişmiyor

### ISSUE THREAD

**Issue by Hime-Dev** [ayberktandogan/ForFansubs-ReactApp---Front-end#3]
Site sorunsuz bir şekilde kuruldu fakat sayfaların kendi içinde ekip-alım sayfası,arama,index gibi sayfaların js'lerinde yapılan değişiklikler değişmiyor.

**Comment by ayberktandogan** [comment]
https://ayberktandogan.github.io/ForFansubs-Wiki/yukleme-talimatlari/

Burada belirttiğim gibi dosyaları oluşturduktan sonra dev ortamında açıp, istediğiniz dosyadan istediğiniz kodu değiştirip, değişikliklerinizi gerçek zamanlı görebiliyor olmanız gerekiyor. Sonuçta dosyaları cloneluyorsunuz. Değişikliklerin gerçekleşmesini engelleme gibi bir durum söz konusu değil.

Ayrıca ekip alımları sayfasını yakın zamanda dinamik yapmaya çalışacağım. Şu anda kötü bir şekilde ön tarafta statik olarak ekli.

**Comment by Zamion101** [comment]
Apache2 mod_proxy ile 5000 portu icin reverse_proxy kuruyorum dev ortaminda d production ortaminda da acsam degisikliklerim sadece konsol uzerinden dev ortami acinca etki etmekte. Bunu duzeltmek icin onerebileceginiz bir sey var midir?

**Comment by ayberktandogan** [comment]
Sorununuzu hala tam olarak anlamadım.

Bu paket https://github.com/facebook/create-react-app boilerplate'ini kullanıyor. Bulunduğu klasörden `npm start` olarak çalıştırırsanız, dev ortamını hot reload açık kurar. Bu sırada Node sunucusunu da ister production isterseniz de development env'inde açabilirsiniz fark etmez. React dev aksini belirtmediğiniz sürece 3000, Node sunucusu da aksini belirtmediğiniz sürece 5000'de çalışır.

Sayfalar üstünde istediğiniz değişiklikleri yaptıktan sonra (index'e bir şey eklemek, search kısmına bir şey eklemek vs.), `npm run build` yapıp, çıkan build dosyası içindekileri yine wiki'de belirttiğim şekilde Node sunucu dosyasının içerisindeki gerekli yere atmanız gerekiyor. Ondan sonra sunucuyu istediğiniz portta hostlayabilirsiniz.

Hem React hem de Node sunucusunu ayrı ayrı serve etmenize gerek yok. Node sunucusu bunu tek başına yapıyor zaten.

**Comment by Hime-Dev** [comment]
yardımlarınız için teşekkür ederim, fakat bir kaç sorunum daha var ayberk, öncellikle manga bölümünde api kullanarak veri çekmiyor işin tuhafı hatada vermiyor hiçbir şey yapmıyor. Bunun yanı sıra sanırsam dosyalara koymayı unutmuşsun fornt-end-admin paketinde /src/static klasörü yok  haberin olsun. En yakın zamanda tüm güncellemelerini bekliyorum umarım manga sorunuda çözersin. Çalışmanda başarılar dilerim.

**Comment by ayberktandogan** [comment]
Manga hatasını düzelttim, söylediğiniz için teşekkürler.

Admindeki static dosyasını sizin oluşturmanız gerektiğini Wiki'de alakalı bölümde bahsetmiştim. Client'ta yapmanız gerekenlerin aynısını orada da yapıyorsunuz.

**Comment by usameavci** [comment]
> Apache2 mod_proxy ile 5000 portu icin reverse_proxy kuruyorum dev ortaminda d production ortaminda da acsam degisikliklerim sadece konsol uzerinden dev ortami acinca etki etmekte. Bunu duzeltmek icin onerebileceginiz bir sey var midir?

Chrome ön belleklemesinden kaynaklı bir durum, development yaparken <kbd>Öğeyi Denetle - Inspect Element</kbd> > <kbd>Ağ-Network</kbd> kısmından **Disable Cache** açık tutmalısın. Öğeyi denetleyi açmadıysan <kbd>CMD+Shift+R</kbd>-<kbd>CTRL+Shift+R</kbd> ile sayfayı yenilemen lazım.

![image](https://user-images.githubusercontent.com/6714468/70595188-c4bdd700-1bf3-11ea-88b0-240733aff629.png)
