### ISSUE TITLE
REACT_APP_SSS_PAGE_TEXT= Alt alta yazma sorunu

### ISSUE THREAD

**Issue by Hime-Dev** [ayberktandogan/ForFansubs-ReactApp---Front-end#5]
Evet .env dosyasında ki REACT_APP_SSS_PAGE_TEXT= bunu env de sadece bir satır veya tek metin şekilde yazabiliyoruz. Benim istediğim aşağıda ki örnekte ki gibi yazmak nasıl yapacağımı bulamadım <br> ve \n denedim işe yaramıyor maalesef.

Örnek:
1-Soru 1
-Soru cevap
2-Soru 2

**Comment by ayberktandogan** [comment]
PuzzleSubs için kullanılan [SSS](https://puzzlesubs.com/sss) yazısı aşağıdaki gibidir. 

`
1-) Hesabıma giriş yapamıyorum/Hesap açamıyorum, neden?\nForumda kulladığımız sistem ile bu sistem arasında hiçbir bağlantı yoktur, yani forumdaki hesaplarınızla bu sisteme giriş yapamazsınız. Şu aşamada hesap açmanın size hiçbir artısı olmayacaktır. Eğer ilerde üyeliğin gerekli olduğunu düşünürsek kayıtları açıp size haber vereceğiz, merak etmeyin.\n\n2-) "Şu şu" animenin indirme-izlenme linki eklenmemiş, neden?\nGüncel seriler için: Çeviri ne zaman gelecek diye sormayın lütfen, çünkü bizim de çevirinin ne zaman geleceğinden, ne zaman encode ve upload edileceğinden en ufak bir fikrimiz yok.\n\n3-) Siteye yeni özellikler gelecek mi, nereden yeni fikir verebilirim?\nŞimdilik basit ve sade bir site olarak kalmayı düşünüyoruz. Öncelikli hedefimiz hem bilgisayar hem de telefonlarda düzgünce girebileceğiniz, işlevsel bir site oluşturmak ve bunu hatalardan arındırmak. Ama eğer sunmak istediğiniz bir fikriniz varsa, bize her zaman Discord sunucumuzdan ulaşabilirsiniz.\n(Kanal: #site-hatalari-puzzlesubs-beta)\n\n4-) Sitede coin miner gibi şeyler olacak mı?\nCoin miner gibi CPU'nuzu zorlayacak, sitenin kullanabilirliğini azaltacak bir şey eklemeyi, sitede bulunduğunuz süre boyunca zorla kullandırtmayı düşünmüyoruz. İlerde, sadece sizin vereceğiniz izinle çalışacak bir şeyler eklemeyi düşünebiliriz ama.
`

**Comment by Hime-Dev** [comment]
yukardaki ss yazısını denedim fakat sistemde \n fonkisyonu çalışmıyor kendinizde deneyebilirsiniz. normal olduğu gibi \n yazıyor. @ayberktandogan

**Comment by ayberktandogan** [comment]
Texti yazdığınız div'de `white-space: pre-wrap;` propertysi olduğu sürece yukardaki yazı da çalışıyor, sizin yazcağınız da çalışacak. Denemem gereken bir şey yok. Canlıda olan texti attım size.

**Comment by Hime-Dev** [comment]
Peki teşekkürler yardımların için.
