### ISSUE TITLE
Yeni Sayfa

### ISSUE THREAD

**Issue by Hime-Dev** [ayberktandogan/ForFansubs-ReactApp---Front-end#6]
Kendim ek olarak sayfa açmak istedim ekip alım gibi sol tarafta ki menü de sayfa ikonunu ve adını oluşturdum hatta yönlendirmelerde tamam istediğim linke yönlendiriyor fakat sayfanın kendisi oluşmadı nasıl oluşturabilirim yeni sayfa (ekip alım sayfasını kopyalamak için sorulmuştur bu soru.)

**Comment by ayberktandogan** [comment]
Bunun için React'in resmi dökümantasyonlarına bakabilirsiniz. Bu paketle ilgili bir soru olmadığı için cevaplayamayacağım.

**Comment by Hime-Dev** [comment]
tamamdır bende biraz abartıp her şeyi sordum ama genel olarak çözdüm routes kısmındaki ayarları eksiksiz yapınca.
